import { Geist, Geist_Mono } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import Header from '@/app/components/header'
import Footer from '@/app/components/footer'
import Script from 'next/script'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

const polySans = localFont({
	src: './fonts/PolySans Median.ttf',
	variable: '--font-poly-sans',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const GoogleAnalytics = () => {
	return (
		<>
			<Script async src={'https://www.googletagmanager.com/gtag/js?id=G-2V11506VEC'} />
			<Script
				id="ga-script"
				dangerouslySetInnerHTML={{
					__html: `
						window.dataLayer = window.dataLayer || [];
						function gtag(){dataLayer.push(arguments);}
						gtag('js', new Date());
						gtag('config', 'G-2V11506VEC');
					`,
				}}
			/>
		</>
	)
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<script
					type="text/javascript"
					dangerouslySetInnerHTML={{
					__html: `
						window.$crisp = [];
						window.CRISP_WEBSITE_ID = "0863f567-94c5-46b7-9e36-74d10ab8a0c9";
						(function() {
						var d = document;
						var s = d.createElement("script");
						s.src = "https://client.crisp.chat/l.js";
						s.async = 1;
						d.getElementsByTagName("head")[0].appendChild(s);
						})();
					`,
					}}
				/>
				<script type="text/javascript" src="//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js" async></script>
			</head>
			<body
				className={`${geistMono.variable} ${polySans.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
			>
				<GoogleAnalytics />
				<Header />

				{children}
				
				<Footer />
			</body>
		</html>
	)
}
