import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased font-[family-name:var(--font-geist-sans)]`}
			>
				<header className="fixed z-10 top-4 left-0 w-full px-16 flex justify-between items-center">
					<Link href="/" className="">
						<img src="wavegrid-logo.svg" width={60} />
					</Link>
					<nav className="absolute left-1/2 transform -translate-x-1/2 px-8 py-2 bg-white/50 rounded-2xl backdrop-blur-xl backdrop-saturate-150 [clip-path:inset(12px 12px 12px 12px round 12px)]">
						<ul className="flex gap-8 text-gray-600 text-sm font-medium">
							<li>
								<Link href="/">Home</Link>
							</li>
							<li>
								<Link href="/about">About</Link>
							</li>
							<li>
								<Link href="/#reviews">Reviews</Link>
							</li>
							<li>
								<Link href="/contact">Contact</Link>
							</li>
						</ul>
					</nav>
					<Link href="/contact" className="py-2 px-4 bg-blue-600 rounded-2xl text-white text-sm font-medium">Book a call</Link>
				</header>

				{children}

				<footer className="bg-black py-24 px-16">
					<div className="flex flex-col lg:flex-row max-w-7xl mx-auto">
						<div className="w-1/4">
							<Link href="/" className="">
								<img src="wavegrid-logo-white.svg" width={60} />
							</Link>
						</div>
						<div className="w-1/2 text-white">
							<nav className="mx-auto">
								<ul className="flex justify-center gap-8 text-white text-center text-sm font-medium">
									<li>
										<Link href="/">Home</Link>
									</li>
									<li>
										<Link href="/about">About</Link>
									</li>
									<li>
										<Link href="/#reviews">Reviews</Link>
									</li>
									<li>
										<Link href="/contact">Contact</Link>
									</li>
								</ul>
							</nav>
						</div>
						<div className="w-1/4 text-white text-right text-sm font-medium">
							<p>+1 (514) 562-7301</p>
							<p>hello@wavegridwebdesign.com</p>
							<p>Toronto, ON, Canada</p>
						</div>
					</div>
				</footer>
			</body>
		</html>
	)
}
